version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres_network
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: pgadmin4
    ports:
      - "5480:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres_network
    depends_on:
      - postgres
networks:
  postgres_network:
    driver: bridge
volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
