version: '3.9'
services:
  postgres:
    container_name: postgres14.1_container
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - database
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '80:80'
    networks:
      - database
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  database:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local

